name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOWY3ZTc3MTUtZjE1MC00YmE0LWFlNDMtMzE3ZjAxOGM3ZTRmIiwidGVuYW50X2lkIjoiMTg3YjVhMTBhNzIwODMzYzIwMzA2Yzk5Y2NhM2EzZGMyZTBmODFlZTJkMmRhOTdlODI3MmNjNTg3ZWYyNDk1NSIsImludGVybmFsX3NlY3JldCI6IjY0OTE5MzcwLWE1ZGYtNDViNi04ODNlLWNjOGI3NzEwYmUxMSJ9.tJNWpl1g7oyrHP3hToVMK6VCDbsbYPm7-6HdtJx3YKI"
JWT_SECRET =  "d3e7ca504dd0636a9f76a4186c20c53ee580257a90f88dfcc24ac205f90b1213"